name: ci-node
on:
  pull_request:
    branches: 
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Sonar Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}